import { DEFAULT_TRAINING_STARTED_ON, DEFAULT_TRAINING_WEEKS, type TrainingExercise, type TrainingPlan, type TrainingSession } from "./training.ts";

function ex(
  id: string,
  name: string,
  prescription: string,
  systemId: string | null = null,
): TrainingExercise {
  return { id, name, prescription, systemId };
}

function session(input: Omit<TrainingSession, "weeklyGoal"> & { weeklyGoal?: number | null }): TrainingSession {
  return { ...input, weeklyGoal: input.weeklyGoal ?? null };
}

const STRENGTH = "1x12 calentamiento, 2x6 efectivas, 3xfallo (menos peso, 10 s entre series)";
const LADDER = "1x calentamiento (50% RM), 1x8 (70% RM), 2x4 (90% RM)";

export const seedTraining: TrainingPlan = {
  startedOn: DEFAULT_TRAINING_STARTED_ON,
  weekCount: DEFAULT_TRAINING_WEEKS,
  notes: [
    "Todos los ejercicios cerca del fallo: 4–6 reps con peso demandante; 12–15 reps con un peso que te deje completar la serie.",
    "Si un ejercicio va 1x12 y luego 2x6, la primera serie es moderada y las dos últimas más pesadas.",
    "No hace falta testear el RM en el gym: estima con una calculadora de repetición máxima.",
  ],
  cardioOptions: [
    "25 min escaladora infinita",
    "25 min elíptica",
    "30 min caminadora con inclinación máxima",
  ],
  cardioWeekdays: [1, 2, 3, 4, 5, 6],
  systems: [
    {
      id: "widow",
      name: "Serie viuda",
      example: "1 serie viuda (50 reps) (80% RM)",
      body: "Agarra un peso muy demandante (cerca del 80% RM) con el que solo hagas 5 a 8 reps. Cada vez que llegues al fallo, pausa 10 segundos y sigue hasta completar las repeticiones del paréntesis.",
    },
    {
      id: "biserie",
      name: "Biserie",
      example: "Curl femoral 4x12 biserie / Extensión cuádriceps 4x12 biserie",
      body: "Haces las reps del primer ejercicio y, sin descansar, las del segundo. Eso es una serie. Repite el número de series que indica el número antes de la X.",
    },
    {
      id: "hold",
      name: "HOLD",
      example: "6x8 (HOLD)",
      body: "1 repetición y sostienes 1 segundo, luego 2 reps y sostienes 2 segundos, y así hasta las reps después de la X. Repite esa ejecución el número de series del sistema.",
    },
    {
      id: "twenty-ones",
      name: "21s",
      example: "3x21s",
      body: "7 reps de la parte baja hasta la mitad, 7 de la mitad a la parte alta y 7 con rango completo, sin descansar. Repite las series que indica el número antes de la X.",
    },
    {
      id: "rest-pause",
      name: "Rest pause",
      example: "3x10 (rest pause)",
      body: "Llegas cerca del fallo, pausas unos segundos y continúas para completar las reps. El peso debe seguir siendo exigente.",
    },
    {
      id: "drop-set",
      name: "Drop set",
      example: "2x (10,12,15) o 3x (10,10,10)",
      body: "Completas el primer número, bajas un poco el peso y sigues con el siguiente, sin descanso largo entre caídas.",
    },
    {
      id: "failure",
      name: "Al fallo",
      example: "3 x fallo / 4xfallo",
      body: "Series hasta que no puedas completar otra repetición con buena forma. En las de pocas reps, el peso tiene que ser alto.",
    },
    {
      id: "strength-wave",
      name: "Progresión de fuerza",
      example: STRENGTH,
      body: "Una serie de calentamiento a 12. Dos series efectivas de 6 con peso serio. Una última al fallo con un poco menos de peso y 10 segundos entre microseries si hace falta.",
    },
    {
      id: "rm-ladder",
      name: "Escalera de RM",
      example: LADDER,
      body: "Calientas al 50% RM, una serie de 8 al 70% y dos de 4 al 90%. El 90% es fuerza: 4 a 6 reps al fallo.",
    },
  ],
  rmNotes: [
    {
      id: "rm-50",
      percent: 50,
      title: "50% RM",
      body: "Peso liviano (fallo entre 15 y 20). Si tu máximo son 100 kg, aquí van 50 kg.",
    },
    {
      id: "rm-70",
      percent: 70,
      title: "70% RM",
      body: "Peso moderado (fallo entre 12 y 15). Si tu máximo son 100 kg, aquí van 70 kg.",
    },
    {
      id: "rm-90",
      percent: 90,
      title: "90% RM",
      body: "Peso alto de fuerza (fallo entre 4 y 6). Si tu máximo son 100 kg, aquí van 90 kg.",
    },
  ],
  sessions: [
    session({
      id: "day-1",
      label: "Día 1",
      focus: "Pecho / espalda / hombro",
      block: "fuerza",
      weekdays: [1],
      weeks: [1, 2, 3, 4],
      exercises: [
        ex("d1-flexiones", "Flexiones en el piso", "4x20"),
        ex("d1-press-plano", "Press banco plano barra", STRENGTH, "strength-wave"),
        ex("d1-press-inclinado", "Press banco inclinado con barra", STRENGTH, "strength-wave"),
        ex("d1-cristos", "Cristos con polea baja", "2x (10, 12, 15)", "drop-set"),
        ex("d1-hammer-pecho", "Hammer para pecho", "1 serie viuda (20 reps) (80% RM)", "widow"),
        ex("d1-laterales-viuda", "Elevaciones laterales mancuerna", "1 serie viuda (50 reps) (60% RM)", "widow"),
        ex("d1-dominadas", "Dominadas", "3 x fallo", "failure"),
        ex("d1-remo-barra", "Remo barra olímpica pesado progresión", STRENGTH, "strength-wave"),
        ex("d1-jalon", "Jalón al pecho polea alta", STRENGTH, "strength-wave"),
        ex("d1-peck-fly", "Peck fly inverso", "2x (10, 12, 15)", "drop-set"),
        ex("d1-laterales-polea", "Laterales con polea baja drop set", "2x (10, 12, 15)", "drop-set"),
      ],
    }),
    session({
      id: "day-2",
      label: "Día 2",
      focus: "Pierna completa",
      block: "fuerza",
      weekdays: [2],
      weeks: [1, 2, 3, 4],
      exercises: [
        ex("d2-hack", "Hack squat o sentadilla péndulo", STRENGTH, "strength-wave"),
        ex("d2-peso-muerto", "Peso muerto con barra", STRENGTH, "strength-wave"),
        ex("d2-ext-cuad", "Extensión de cuádriceps", "3x10 (rest pause)", "rest-pause"),
        ex("d2-curl-acostado", "Curl femoral acostado biserie", "3x10 (rest pause)", "rest-pause"),
        ex("d2-prensa", "Prensa para pierna", STRENGTH, "strength-wave"),
        ex("d2-hip", "Hip thrust con máquina o barra", "1 serie viuda (20 reps) (80% RM)", "widow"),
        ex("d2-abduc-aduc", "Biserie: abductores y aductores", "4x15", "biserie"),
        ex("d2-curl-sentado", "Curl femoral sentado", "2x10"),
        ex("d2-pantorrilla", "Biserie: pantorrilla parado y sentado", "3x20", "biserie"),
      ],
    }),
    session({
      id: "day-3",
      label: "Día 3",
      focus: "Brazos",
      block: "fuerza",
      weekdays: [3],
      weeks: [1, 2, 3, 4],
      exercises: [
        ex("d3-militar", "Biserie: press militar con mancuernas", STRENGTH, "strength-wave"),
        ex("d3-laterales", "Biserie: elevaciones laterales mancuerna", STRENGTH, "strength-wave"),
        ex("d3-face-pull", "Biserie: face pull en el suelo", "3x15", "biserie"),
        ex("d3-laterales-polea", "Biserie: elevaciones laterales polea baja", "3x15", "biserie"),
        ex("d3-curl-z", "Biserie: curl de bíceps polea baja barra Z agarre abierto", "3x8 (rest pause)", "rest-pause"),
        ex("d3-overhead", "Biserie: extensión sobre cabeza progresión", "3x8", "biserie"),
        ex("d3-curl-manc", "Biserie: curl normal mancuerna", "4x fallo", "failure"),
        ex("d3-soga", "Biserie: extensión soga polea alta", "3x10 (rest pause)", "rest-pause"),
        ex("d3-curl-cerrado", "Curl agarre cerrado barra Z", "3x10"),
        ex("d3-martillos", "Martillos con mancuernas", "3x10"),
        ex("d3-ext-uni", "Biserie: extensión unilateral con polea alta", "3x10", "biserie"),
        ex("d3-hercules", "Biserie: curl Hércules", "3x10", "biserie"),
      ],
    }),
    session({
      id: "day-4",
      label: "Día 4",
      focus: "Pierna 1",
      block: "hipertrofia",
      weekdays: [4],
      weeks: [1, 2, 3, 4],
      exercises: [
        ex("d4-sentadilla", "Sentadilla libre o hack", LADDER, "rm-ladder"),
        ex("d4-pullthrough", "Pullthrough", LADDER, "rm-ladder"),
        ex("d4-ext-cuad", "Extensión de cuádriceps biserie", "3x10 (rest pause)", "rest-pause"),
        ex("d4-curl-acostado", "Curl femoral acostado biserie", "3x10 (rest pause)", "rest-pause"),
        ex("d4-prensa", "Prensa", LADDER, "rm-ladder"),
        ex("d4-aductores", "Aductores", "4x15"),
        ex("d4-abductores", "Abductores", "4x15"),
        ex("d4-panto-sentado", "Pantorrilla sentado", "5x10"),
        ex("d4-panto-parado", "Pantorrilla parado", "3x20"),
      ],
    }),
    session({
      id: "day-5-push",
      label: "Día 5",
      focus: "Pecho / hombros / tríceps",
      block: "hipertrofia",
      weekdays: [5],
      weeks: [1, 3],
      exercises: [
        ex("d5a-warmup", "Calentamiento: press máquina o mancuernas peso ligero", "2x20"),
        ex("d5a-press-plano", "Press banco plano barra progresión", LADDER, "rm-ladder"),
        ex("d5a-press-inclinado", "Press banco inclinado barra progresión", LADDER, "rm-ladder"),
        ex("d5a-cruce", "Biserie: cruce con polea baja para pectoral superior", "4x8 (rest pause)", "rest-pause"),
        ex("d5a-laterales", "Elevaciones laterales peso moderado", "4x10 (rest pause)", "rest-pause"),
        ex("d5a-militar", "Press militar con mancuernas progresión", LADDER, "rm-ladder"),
        ex("d5a-face-pull", "Face pull para hombro posterior drop set", "3x (10, 10, 10)", "drop-set"),
        ex("d5a-ext-biserie", "Biserie: extensión overhead con soga / extensión barra Z polea alta", "3x10 (rest pause)", "rest-pause"),
        ex("d5a-skull", "Skull crusher pesado barra Z", "4xfallo", "failure"),
      ],
    }),
    session({
      id: "day-5-pull",
      label: "Día 5",
      focus: "Espalda / hombro / bíceps",
      block: "hipertrofia",
      weekdays: [5],
      weeks: [2, 4],
      exercises: [
        ex("d5b-jalon", "Jalón al pecho polea alta progresión", LADDER, "rm-ladder"),
        ex("d5b-remo-barra", "Remo con barra recta fuerza", LADDER, "rm-ladder"),
        ex("d5b-remo-manc", "Remo a un brazo con mancuerna", "4x fallo", "failure"),
        ex("d5b-pullover", "Pullover con soga polea alta", "3x10 (rest pause)", "rest-pause"),
        ex("d5b-militar", "Press militar pesado con mancuernas ligeras y luego pesadas", "2x15, 2x6"),
        ex("d5b-laterales-21", "Elevaciones laterales polea baja sistema 21", "3x21", "twenty-ones"),
        ex("d5b-laterales-peck", "Biserie: elevaciones laterales con mancuerna / peck fly inverso", "3x10", "biserie"),
        ex("d5b-curl-z", "Curl barra Z", "3x10"),
        ex("d5b-bayesian", "Curl bayesian", "3x10 (rest pause)", "rest-pause"),
        ex("d5b-curl-soga", "Biserie: curl con soga polea baja / curl concentrado mancuerna", "4x15 (rest pause)", "rest-pause"),
      ],
    }),
    session({
      id: "abdomen",
      label: "Abdomen",
      focus: "Core",
      block: "accesorio",
      weekdays: [1, 2, 3, 4, 5, 6, 0],
      weeks: [1, 2, 3, 4],
      weeklyGoal: 2,
      exercises: [
        ex("ab-plancha", "Plancha abdominal", "4x 30 segundos"),
        ex("ab-crunch", "Crunch convencional", "4x15"),
        ex("ab-soga", "Crunch con soga en polea alta", "4x15"),
        ex("ab-inverso", "Crunch inverso en banco", "4x10"),
      ],
    }),
    session({
      id: "forearm",
      label: "Antebrazo",
      focus: "Grip",
      block: "accesorio",
      weekdays: [1, 2, 3, 4, 5, 6, 0],
      weeks: [1, 2, 3, 4],
      weeklyGoal: 2,
      exercises: [
        ex("fa-prono-barra", "Flexión de antebrazo prono con barra", "4x15"),
        ex("fa-supino", "Flexión de antebrazo supino con mancuerna", "4x15"),
        ex("fa-rotaciones", "Rotaciones de antebrazo con mancuerna", "4x15"),
        ex("fa-prono-polea", "Flexión de antebrazo prono con barra polea alta", "4x10"),
      ],
    }),
  ],
};
