import {
  DEFAULT_TRAINING_STARTED_ON,
  DEFAULT_TRAINING_WEEKS,
  TRAINING_CONTENT_VERSION,
  type TrainingExercise,
  type TrainingPlan,
  type TrainingSession,
} from "./training.ts";

function ex(
  id: string,
  name: string,
  prescription: string,
  systemId: string | null = null,
  media: string | string[] | null = null,
): TrainingExercise {
  const list = media == null ? [] : Array.isArray(media) ? media : [media];
  return { id, name, prescription, systemId, media: list };
}

const M = {
  flexiones: "/exercises/flexiones-en-el-piso.gif",
  pressPlano: "/exercises/press-banco-plano-barra.gif",
  pressInclinado: "/exercises/press-banco-inclinado-con-barra.gif",
  cristos: "/exercises/cristos-con-polea-baja.png",
  hammer: "/exercises/hammer-para-pecho.gif",
  lateralesManc: "/exercises/elevaciones-laterales-mancuerna.gif",
  dominadas: "/exercises/dominadas.gif",
  remoBarra: "/exercises/remo-barra-olimpica-pesado-progresion.gif",
  jalon: "/exercises/jalon-al-pecho-polea-alta.gif",
  peckFly: "/exercises/peck-fly-inverso.gif",
  lateralesPolea: "/exercises/laterales-con-polea-baja-drop-set.gif",
  plancha: "/exercises/plancha-abdominal.webp",
  crunch: "/exercises/crunch-convencional.gif",
  crunchSoga: "/exercises/crunch-con-soga-en-polea-alta.gif",
  crunchInverso: "/exercises/crunch-inverso-en-banco.gif",
  flexionProno: "/exercises/flexion-de-antebrazo-prono-con-barra.gif",
  flexionSupino: "/exercises/flexion-de-antebrazo-supino-con-mancuerna.gif",
  extensionesAntebrazo: "/exercises/extensiones-de-antebrazo-con-mancuerna.gif",
  hackSquat: "/exercises/hack-squat.gif",
  sentadillaPendulo: "/exercises/sentadilla-pendulo.gif",
  pesoMuerto: "/exercises/peso-muerto-con-barra.gif",
  extCuad: "/exercises/extension-de-cuadriceps.gif",
  curlAcostado: "/exercises/curl-femoral-acostado.gif",
  curlSentado: "/exercises/curl-femoral-sentado.gif",
  prensa: "/exercises/prensa-para-pierna.jpeg",
  hipThrust: "/exercises/hip-thrust.gif",
  abductores: "/exercises/abductores.gif",
  aductores: "/exercises/aductores.gif",
  pantoParado: "/exercises/pantorrilla-parado.gif",
  pantoSentado: "/exercises/pantorrilla-sentado.gif",
  militar: "/exercises/press-militar-con-mancuernas.gif",
  facePull: "/exercises/face-pull-en-el-suelo.gif",
  curlZAbierto: "/exercises/curl-de-bicep-polea-baja-barra-z-agarre-abierto.gif",
  overhead: "/exercises/extension-sobre-cabeza.gif",
  curlManc: "/exercises/curl-normal-mancuerna.gif",
  extSoga: "/exercises/extension-soga-polea-alta.gif",
  curlCerrado: "/exercises/agarre-cerrado-barra-z.gif",
  martillos: "/exercises/martillos-con-mancuernas.gif",
  extUni: "/exercises/extension-unilateral-con-polea-alta.gif",
  curlHercules: "/exercises/curl-hercules.gif",
  pullthrough: "/exercises/pullthrough.gif",
  skull: "/exercises/skull-crusher-barra-z.gif",
} as const;

function session(input: Omit<TrainingSession, "weeklyGoal"> & { weeklyGoal?: number | null }): TrainingSession {
  return { ...input, weeklyGoal: input.weeklyGoal ?? null };
}

const STRENGTH = "1x12 calentamiento, 2x6 EFECTIVAS, 3xfallo (Menos peso 10 segundos descanso entre serie)";
const LADDER = "1x calentamiento (50% Rm), 1x8 (70% Rm), 2x 4 (90% Rm)";

export const seedTraining: TrainingPlan = {
  startedOn: DEFAULT_TRAINING_STARTED_ON,
  weekCount: DEFAULT_TRAINING_WEEKS,
  contentVersion: TRAINING_CONTENT_VERSION,
  notes: [
    "Todos los ejercicios cerca del fallo: 4–6 reps con peso demandante; 12–15 reps con un peso que te deje completar la serie.",
    "Si un ejercicio va 1x12 y luego 2x6, la primera serie es moderada y las dos últimas más pesadas.",
    "No hace falta testear el RM en el gym: estima con la calculadora de la pestaña RM (misma fórmula que Soy Powerlifter).",
    "Los días fuertes son lunes a viernes. Sábado y domingo son descanso. Si te decides ir: cardio fácil, recuperar abdomen/antebrazo, o una sesión corta para estimar RM (1 o 2 básicos a 5–8 reps duras, pestaña RM). No hagas 1RM a muerte ni otro día pesado completo.",
    "Abdomen y antebrazo van 2 veces por semana, al final de lunes y viernes. Si quieres otros días, cámbialos en Editar.",
  ],
  cardioOptions: [
    "25 minutos escaladora infinita",
    "25 minutos elíptica",
    "30 minutos caminadora con inclinación máxima",
  ],
  cardioWeekdays: [1, 2, 3, 4, 5],
  systems: [
    {
      id: "widow",
      name: "Serie viuda",
      example: "1 serie viuda (50 reps) (80% RM)",
      body: "Agarra un peso muy demandante (cerca del 80% RM) con el que solo hagas 5 a 8 reps. Cada vez que llegues al fallo, pausa 10 segundos y sigue hasta completar las repeticiones del paréntesis.",
    },
    {
      id: "biserie",
      name: "Biserie",
      example: "Curl femoral 4x12 biserie / Extensión cuádriceps 4x12 biserie",
      body: "Haces las reps del primer ejercicio y, sin descansar, las del segundo. Eso es una serie. Repite el número de series que indica el número antes de la X.",
    },
    {
      id: "hold",
      name: "HOLD",
      example: "6x8 (HOLD)",
      body: "1 repetición y sostienes 1 segundo, luego 2 reps y sostienes 2 segundos, y así hasta las reps después de la X. Repite esa ejecución el número de series del sistema.",
    },
    {
      id: "twenty-ones",
      name: "21s",
      example: "3x21s",
      body: "7 reps de la parte baja hasta la mitad, 7 de la mitad a la parte alta y 7 con rango completo, sin descansar. Repite las series que indica el número antes de la X.",
    },
    {
      id: "rest-pause",
      name: "Rest pause",
      example: "3x10 (rest pause)",
      body: "Llegas cerca del fallo, pausas unos segundos y continúas para completar las reps. El peso debe seguir siendo exigente.",
    },
    {
      id: "drop-set",
      name: "Drop set",
      example: "2x (10,12,15) o 3x (10,10,10)",
      body: "Completas el primer número, bajas un poco el peso y sigues con el siguiente, sin descanso largo entre caídas.",
    },
    {
      id: "failure",
      name: "Al fallo",
      example: "3 x fallo / 4xfallo",
      body: "Series hasta que no puedas completar otra repetición con buena forma. En las de pocas reps, el peso tiene que ser alto.",
    },
    {
      id: "strength-wave",
      name: "Progresión de fuerza",
      example: STRENGTH,
      body: "Una serie de calentamiento a 12. Dos series efectivas de 6 con peso serio. Una última al fallo con un poco menos de peso y 10 segundos entre microseries si hace falta.",
    },
    {
      id: "rm-ladder",
      name: "Escalera de RM",
      example: LADDER,
      body: "Calientas al 50% RM, una serie de 8 al 70% y dos de 4 al 90%. El 90% es fuerza: 4 a 6 reps al fallo.",
    },
  ],
  rmNotes: [
    {
      id: "rm-50",
      percent: 50,
      title: "50% RM",
      body: "Peso liviano (fallo entre 15 y 20). Si tu máximo son 100 kg, aquí van 50 kg.",
    },
    {
      id: "rm-70",
      percent: 70,
      title: "70% RM",
      body: "Peso moderado (fallo entre 12 y 15). Si tu máximo son 100 kg, aquí van 70 kg.",
    },
    {
      id: "rm-90",
      percent: 90,
      title: "90% RM",
      body: "Peso alto de fuerza (fallo entre 4 y 6). Si tu máximo son 100 kg, aquí van 90 kg.",
    },
  ],
  sessions: [
    session({
      id: "day-1",
      label: "Día 1",
      focus: "Pecho / espalda / hombro",
      block: "fuerza",
      weekdays: [1],
      weeks: [1, 2, 3, 4],
      exercises: [
        ex("d1-flexiones", "Flexiones en el piso", "4x20", null, M.flexiones),
        ex("d1-press-plano", "Press banco plano barra", STRENGTH, "strength-wave", M.pressPlano),
        ex("d1-press-inclinado", "Press banco inclinado con barra", STRENGTH, "strength-wave", M.pressInclinado),
        ex("d1-cristos", "Cristos con polea baja", "2X (10, 12, 15)", "drop-set", M.cristos),
        ex("d1-hammer-pecho", "Hammer para pecho", "1 serie viuda (20 reps) (80% RM)", "widow", M.hammer),
        ex("d1-laterales-viuda", "Elevaciones laterales mancuerna", "1 serie viuda (50 reps) (60% RM)", "widow", M.lateralesManc),
        ex("d1-dominadas", "Dominadas", "3 x fallo", "failure", M.dominadas),
        ex("d1-remo-barra", "Remo barra olímpica pesado progresión", STRENGTH, "strength-wave", M.remoBarra),
        ex("d1-jalon", "Jalón al pecho polea alta", STRENGTH, "strength-wave", M.jalon),
        ex("d1-peck-fly", "Peck fly inverso", "2X (10, 12, 15)", "drop-set", M.peckFly),
        ex("d1-laterales-polea", "Laterales con polea baja drop set", "2X (10, 12, 15)", "drop-set", M.lateralesPolea),
      ],
    }),
    session({
      id: "day-2",
      label: "Día 2",
      focus: "Pierna completa",
      block: "fuerza",
      weekdays: [2],
      weeks: [1, 2, 3, 4],
      exercises: [
        ex("d2-hack", "Hack squat o sentadilla péndulo", STRENGTH, "strength-wave", [
          M.hackSquat,
          M.sentadillaPendulo,
        ]),
        ex("d2-peso-muerto", "Peso muerto con barra", STRENGTH, "strength-wave", M.pesoMuerto),
        ex("d2-ext-cuad", "Extensión de cuadriceps", "3x10 (rest pause)", "rest-pause", M.extCuad),
        ex("d2-curl-acostado", "Curl femoral acostado biserie", "3x10 (rest pause)", "rest-pause", M.curlAcostado),
        ex("d2-prensa", "Prensa para pierna", STRENGTH, "strength-wave", M.prensa),
        ex("d2-hip", "Hip thrust con maquina o barra", "1 serie viuda (20 reps) (80% RM)", "widow", M.hipThrust),
        ex("d2-abduc-aduc", "Biserie: Abductores y Aductores", "4x15", "biserie", [M.abductores, M.aductores]),
        ex("d2-curl-sentado", "Curl femoral sentado", "2x10", null, M.curlSentado),
        ex("d2-pantorrilla", "Biserie: Pantorrilla parado y sentado", "3x20", "biserie", [
          M.pantoParado,
          M.pantoSentado,
        ]),
      ],
    }),
    session({
      id: "day-3",
      label: "Día 3",
      focus: "Brazos",
      block: "fuerza",
      weekdays: [3],
      weeks: [1, 2, 3, 4],
      exercises: [
        ex("d3-militar", "Biserie: Press militar con mancuernas", STRENGTH, "strength-wave", M.militar),
        ex("d3-laterales", "Biserie: Elevaciones laterales mancuerna", STRENGTH, "strength-wave", M.lateralesManc),
        ex("d3-face-pull", "Biserie: Face pull en el suelo", "3x15", "biserie", M.facePull),
        ex("d3-laterales-polea", "Biserie: Elevaciones laterales polea baja", "3x15", "biserie", M.lateralesPolea),
        ex("d3-curl-z", "Biserie: Curl de bicep polea baja barra z agarre abierto", "3x8 (Rest pause)", "rest-pause", M.curlZAbierto),
        ex("d3-overhead", "Biserie: Extension sobre cabeza progresión", "3x8", "biserie", M.overhead),
        ex("d3-curl-manc", "Biserie: Curl normal mancuerna", "4x fallo", "failure", M.curlManc),
        ex("d3-soga", "Biserie: Extensión soga polea alta", "3x10 (rest pause)", "rest-pause", M.extSoga),
        ex("d3-curl-cerrado", "Curl agarre cerrado barra Z", "3x10", null, M.curlCerrado),
        ex("d3-martillos", "Martillos con mancuernas", "3x10", null, M.martillos),
        ex("d3-ext-uni", "Biserie: Extensión unilateral con polea alta", "3x10", "biserie", M.extUni),
        ex("d3-hercules", "Biserie: Curl hercules", "3x10", "biserie", M.curlHercules),
      ],
    }),
    session({
      id: "day-4",
      label: "Día 4",
      focus: "Pierna 1",
      block: "hipertrofia",
      weekdays: [4],
      weeks: [1, 2, 3, 4],
      exercises: [
        ex("d4-sentadilla", "Sentadilla libre o Hack", LADDER, "rm-ladder", M.sentadillaPendulo),
        ex("d4-pullthrough", "Pullthrough", LADDER, "rm-ladder", M.pullthrough),
        ex("d4-ext-cuad", "Extensión de cuadriceps biserie", "3x10 (rest pause)", "rest-pause", M.extCuad),
        ex("d4-curl-acostado", "Curl femoral acostado biserie", "3x10 (rest pause)", "rest-pause", M.curlAcostado),
        ex("d4-prensa", "Prensa", LADDER, "rm-ladder", M.prensa),
        ex("d4-aductores", "Aductores", "4x15", null, M.aductores),
        ex("d4-abductores", "Abductores", "4x15", null, M.abductores),
        ex("d4-panto-sentado", "Pantorrilla sentado", "5x10", null, M.pantoSentado),
        ex("d4-panto-parado", "Pantorrilla parado", "3x20", null, M.pantoParado),
      ],
    }),
    session({
      id: "day-5-push",
      label: "Día 5 (sem. 1 y 3)",
      focus: "Pecho / hombros / tríceps",
      block: "hipertrofia",
      weekdays: [5],
      weeks: [1, 3],
      exercises: [
        ex("d5a-warmup", "Calentamiento: Press máquina o mancuernas peso ligero", "2x20", null, M.militar),
        ex("d5a-press-plano", "Press banco plano barra progresión", LADDER, "rm-ladder", M.pressPlano),
        ex("d5a-press-inclinado", "Press banco inclinado barra progresión", LADDER, "rm-ladder", M.pressInclinado),
        ex("d5a-cruce", "Biserie: Cruce con polea baja para pectoral superior", "4x8 (rest pause)", "rest-pause"),
        ex("d5a-laterales", "Elevaciones laterales peso moderado", "4x10 (rest pause)", "rest-pause", M.lateralesManc),
        ex("d5a-militar", "Press militar con mancuernas progresión", LADDER, "rm-ladder", M.militar),
        ex("d5a-face-pull", "Face pull para hombro posterior drop set", "3x (10,10,10)", "drop-set", M.facePull),
        ex("d5a-ext-biserie", "Biserie: Extensión overhead con soga / Extensión barra z polea alta", "3x10 (rest pause)", "rest-pause", [
          M.overhead,
          M.extSoga,
        ]),
        ex("d5a-skull", "Skull crusher pesado barra z", "4xfallo", "failure", M.skull),
      ],
    }),
    session({
      id: "day-5-pull",
      label: "Día 5 (sem. 2 y 4)",
      focus: "Espalda / hombro / bíceps",
      block: "hipertrofia",
      weekdays: [5],
      weeks: [2, 4],
      exercises: [
        ex("d5b-jalon", "Jalón al pecho polea alta progresión", LADDER, "rm-ladder", M.jalon),
        ex("d5b-remo-barra", "Remo con barra recta fuerza", LADDER, "rm-ladder", M.remoBarra),
        ex("d5b-remo-manc", "Remo a un brazo con mancuerna", "4x fallo", "failure"),
        ex("d5b-pullover", "Pull over con soga polea alta", "3x10 (rest pause)", "rest-pause"),
        ex("d5b-militar", "Pres militar pesado con mancuernas ligeras y luego pesadas", "2x15, 2x6", null, M.militar),
        ex("d5b-laterales-21", "Elevaciones laterales polea baja sistema 21", "3x21", "twenty-ones", M.lateralesPolea),
        ex("d5b-laterales-peck", "Biserie: Elevaciones laterales con mancuerna / Peck fly inverso", "3x10", "biserie", [
          M.lateralesManc,
          M.peckFly,
        ]),
        ex("d5b-curl-z", "Curl barra z", "3x10", null, M.curlCerrado),
        ex("d5b-bayesian", "Curl bayesian", "3x10 (rest pause)", "rest-pause"),
        ex("d5b-curl-soga", "Biserie: Curl con soga polea baja / Curl concentrado mancuerna", "4x15 (Rest pause)", "rest-pause"),
      ],
    }),
    session({
      id: "abdomen",
      label: "Abdomen",
      focus: "Core",
      block: "accesorio",
      weekdays: [1, 5],
      weeks: [1, 2, 3, 4],
      weeklyGoal: 2,
      exercises: [
        ex("ab-plancha", "Plancha abdominal", "4x 30 segundos", null, M.plancha),
        ex("ab-crunch", "Crunch convencional", "4x15", null, M.crunch),
        ex("ab-soga", "Crunch con soga en polea alta", "4x15", null, M.crunchSoga),
        ex("ab-inverso", "Crunch inverso en banco", "4x10", null, M.crunchInverso),
      ],
    }),
    session({
      id: "forearm",
      label: "Antebrazo",
      focus: "Grip",
      block: "accesorio",
      weekdays: [1, 5],
      weeks: [1, 2, 3, 4],
      weeklyGoal: 2,
      exercises: [
        ex("fa-prono-barra", "Flexión de antebrazo prono con barra", "4x15", null, M.flexionProno),
        ex("fa-supino", "Flexión de antebrazo supino con mancuerna", "4x15", null, M.flexionSupino),
        ex("fa-rotaciones", "Extensiones de antebrazo con mancuerna", "4x15", null, M.extensionesAntebrazo),
        ex("fa-prono-polea", "Extensión de antebrazo prono con barra", "4x10"),
      ],
    }),
  ],
};
